### ISSUE TITLE
Admin verification error allows injecting content

### ISSUE THREAD

**Issue by saltybeagle** [UNLSiteMaster/site_master#126]
The error messages encountered during verification (e.g. 404) are displayed to the end user, which allows XSS and content injection.
![screen shot 2017-04-10 at 10 31 17 am](https://cloud.githubusercontent.com/assets/92284/24869787/fabc4000-1dd9-11e7-8d38-d10ddc8c18c2.png)

**Comment by mfairchild365** [comment]
This is terrible. Thank you for pointing it out, @saltybeagle. Working on a fix now.

**Comment by mfairchild365** [comment]
This was due to a server misconfiguration, open_basedir was preventing the output from being written to /dev/null so PHP tried to be smart and instead sent it to standard out (the webpage).

This has been fixed in production.
