### ISSUE TITLE
Site Verification is not working got colorado.edu sites

### ISSUE THREAD

**Issue by kreynen** [UNLSiteMaster/site_master#148]
Not sure if this is the right issue queue.  I was able to authenticate via InCommon, but I've tried both the file and the metatag verification using the options provided by https://www.drupal.org/project/site_verify 

https://www.colorado.edu/webcentral/sitemaster_v_a188be672e9dd34ee5b75b56e5709cc7.txt

![view-source_https___www_colorado_edu_webcentral_](https://user-images.githubusercontent.com/385234/43155923-f4cc913a-8f35-11e8-9e73-10b2c0e3c0ee.png)

The verification step always fails.

**Comment by kreynen** [comment]
I purged varnish for that site after making the change, but I'm still seeing 404s when requesting that url using curl or wget myself.  Something is definitely wrong on our end.  Sorry.

**Comment by mfairchild365** [comment]
No problem, I appreciate that you opened an issue to get some feedback. :)
