### ISSUE TITLE
Approve Pending Roles is missing a CSRF token

### ISSUE THREAD

**Issue by mfairchild365** [UNLSiteMaster/site_master#154]
So submitting the form always fails.

https://github.com/UNLSiteMaster/site_master/blob/master/www/templates/html/SiteMaster/Core/Registry/Site/MembersForm.tpl.php should be edited to include something like https://github.com/UNLSiteMaster/site_master/blob/d14162307e26acbc7c38fbeb608984aea7e0647c/www/templates/html/SiteMaster/Core/Auditor/Site/Page/ScanForm.tpl.php#L6

**Comment by ericras** [comment]
This form fails too: www/templates/html/SiteMaster/Core/Registry/Site/JoinSiteForm.tpl.php

**Comment by ericras** [comment]
This one too: https://github.com/UNLSiteMaster/site_master/blob/master/www/templates/html/SiteMaster/Core/Registry/Site/VerifyForm.tpl.php

**Comment by ericras** [comment]
This one too: https://github.com/UNLSiteMaster/site_master/blob/master/www/templates/html/SiteMaster/Core/Registry/Site/VerifyForm.tpl.php

(although that one worked for me as an admin but end user had problems with it
